apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
  template:
    spec:
      imagePullSecrets:  
      - name: dockerhub-secret
      containers:
      - name: flask-app
        image: ${DOCKERHUB_USERNAME}/flask-app:${IMAGE_TAG} 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
